const DATE_FORMAT_SHORT = 'YYYY';
const DATE_FORMAT_FULL = 'DD MMMM YYYY';
const COMMENT_FORMS = ['comment', 'comments'];
const FILMS_COUNT = 5;
const DAYJS_DURATION_FORMAT = {
  SHORT: 'm[m]',
  FULL: 'H[h] m[m]'
};

export {
  DATE_FORMAT_SHORT,
  DATE_FORMAT_FULL,
  COMMENT_FORMS,
  FILMS_COUNT,
  DAYJS_DURATION_FORMAT
};
